//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamilyAuto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceOrder
    {
        public int Id { get; set; }
        public int Price { get; set; }
        public bool Paid { get; set; }
        public System.DateTime OrderedOnDate { get; set; }
        public System.DateTime DueDate { get; set; }
        public System.DateTime DeliveredDate { get; set; }
        public int ServiceId { get; set; }
        public int CustomerId { get; set; }
    
        public virtual Articles Articles { get; set; }
        public virtual Customers Customers { get; set; }
    }
}
