//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamilyAuto.Models
{
    using System;
    
    public enum TypeEnum : int
    {
        AWD = 0,
        Commercial = 1,
        Convertible = 2,
        Coupe = 3,
        Hatchback = 4,
        Hybrid = 5,
        Luxury = 6,
        Sedan = 7,
        SUV = 8,
        Truck = 9,
        Minivan = 10,
        Wagon = 11
    }
}
