//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamilyAuto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        public int Id { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public string Variant { get; set; }
        public string Condition { get; set; }
        public string Type { get; set; }
        public string Description { get; set; }
        public System.DateTime DateUploaded { get; set; }
    
        public virtual VehicleEngine VehicleEngine { get; set; }
        public virtual VehicleFeature VehicleFeature { get; set; }
        public virtual VehicleHistory VehicleHistory { get; set; }
    }
}
