//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamilyAuto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehicle()
        {
            this.VehiclePictures = new HashSet<VehiclePicture>();
            this.SoldVehicles = new HashSet<SoldVehicles>();
            this.Comission = new HashSet<Comission>();
            this.FavoriteVehicle = new HashSet<FavoriteVehicle>();
        }
    
        public int Id { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public string Variant { get; set; }
        public string Condition { get; set; }
        public TypeEnum Type { get; set; }
        public string Description { get; set; }
        public Nullable<int> Price { get; set; }
        public System.DateTime DateUploaded { get; set; }
        public bool Sold { get; set; }
    
        public virtual VehicleEngine VehicleEngine { get; set; }
        public virtual VehicleFeature VehicleFeature { get; set; }
        public virtual VehicleHistory VehicleHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehiclePicture> VehiclePictures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SoldVehicles> SoldVehicles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comission> Comission { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FavoriteVehicle> FavoriteVehicle { get; set; }
    }
}
