//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamilyAuto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleEngine
    {
        public int Id { get; set; }
        public string FuelType { get; set; }
        public string Transmission { get; set; }
        public Nullable<int> CubicCapacity { get; set; }
        public Nullable<int> Power { get; set; }
        public string FuelConsumption { get; set; }
        public string EmissionClass { get; set; }
        public string EmissionSticker { get; set; }
        public int VehicleID { get; set; }
    
        public virtual Vehicle Vehicle { get; set; }
    }
}
